name: update

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch: # 允许手动触发

permissions:
  contents: write  # 确保 GITHUB_TOKEN 具有写入权限

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests

    - name: Run script
      run: |
        python config/update.py

    - name: List files in workspace
      run: ls -la

    - name: Git status
      run: git status

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Commit and Push changes
      run: |
        git add $(pwd)/my02.txt  # 使用绝对路径确保路径正确
        git commit -m "Update my02 with new streams" --allow-empty
        git push origin HEAD:master  # 如果使用的是其他分支，请修改
